language: android

android:
  components:
    - platform-tools
    - build-tools-27.1.1
    - android-27

script:
  - ./gradlew build connectedCheck

script:
  - chmod +x ./gradlew build connectedCheck
